language: go
sudo: false
matrix:
  include:
  - go: tip
  allow_failures:
  - go: tip
script:
- "./.travis/build-all"
deploy:
  provider: releases
  api_key:
    secure: kTNBJNBJ0YMrsaOpWd+wqNQZ/thZhJ74n0gVxzCvyIJkSZJOr6WIP1qTW+TXIZ/L3txST34mvvV2d5fWONe4NrJWvTpHhHq1pA8Rs6JmYucWaNuoI82ZTX6bDVXVW0pWy7koD5qarc287MxMOV0Jz7Btavxu6EHLAr2C1c2xRRCAEyI/f3he8pPrlK3XPJbgwYGoaS5SBeTVqorag9r6HNVMe535L+P90mx8jounfTyBoZWphSKNexJUaPzLsM1vX2uwJpYXScKIVuxtE9NGrxsXzRpK9dQzoZJNGATGhQPGSw7JcmRkk/CbFj8KqibRlrfgHTQ/MKOMLkz+BP6NM/1HrGziRqKoUmwhwjqOZIFD/jsY9gj+Tspt6lyzo+DJpQzAZj/EKuWUnpZ0bRY/hlQ9w7iaVSyxJu1v7imWoqirugBaP4ZlZuVV0GDCRRutmecK0IR6OB5lHO4UPfM5OuCp6UXXCdw5A/xv0pbjxNM1GmabkgQAmWFWtd3iL/kanhTZ54Mny/kPmaSVwtJXPfx1N51Cr1BuSBM1jAMNQ5VG8Y2BCTUhMEf2As3k2ew0VcS+ptyWM7y8N3dQuiB/PVIY34fsrS8/fN1LTUMozuRp9bhLRScINKu7rjRoK0/Xaaui0KNzs6YBg3mZhLi9/V0q2hn8pw4+Eil4tqD5vkA=
  file_glob: true
  file: knownfs-*
  skip_cleanup: true
  on:
    tags: true
